import type { Metadata } from "next";
import { Playfair_Display, Source_Serif_4, DM_Mono } from "next/font/google";
import "./globals.css";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
  weight: ["300", "400", "600"],
  display: "swap",
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["300", "400"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://starfagrunnur.is"),
  title: {
    default: "Starfagrunnur — Opinn gagnagrunnur um störf og hæfni",
    template: "%s",
  },
  description:
    "Starfagrunnur er opinn gagnagrunnur og API um íslenskt starfakerfi, byggður á ÍSTARF21 og ESCO. Leitaðu, skoðaðu og tengdu starfaflokka, hæfni og færni.",
  keywords: [
    "starfagrunnur",
    "ÍSTARF21",
    "ESCO",
    "störf",
    "hæfni",
    "API",
    "Ísland",
  ],
  alternates: {
    canonical: "/",
    languages: {
      is: "/",
      "x-default": "/",
    },
  },
  // Images are auto-generated by src/app/opengraph-image.tsx (and twitter-image.tsx if added).
  openGraph: {
    title: "Starfagrunnur — Opinn gagnagrunnur um störf og hæfni",
    description:
      "ÍSTARF21 og ESCO sameinað í opið REST API. 578 starfaflokkar, 3.039 ESCO starfsheiti, 13.939 hæfnieiningar.",
    url: "https://starfagrunnur.is",
    siteName: "Starfagrunnur",
    locale: "is_IS",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Starfagrunnur — Opinn gagnagrunnur um störf og hæfni",
    description:
      "ÍSTARF21 og ESCO sameinað í opið REST API. Leitaðu, skoðaðu og tengdu starfaflokka, hæfni og færni.",
  },
};

// Structured data: Dataset + WebSite + Organization.
// Critical for Google Dataset Search, LLM citation confidence, and Knowledge Graph.
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Dataset",
      "@id": "https://starfagrunnur.is/#dataset",
      name: "Starfagrunnur — Íslenskur starfagagnagrunnur",
      alternateName: "Starfagrunnur",
      description:
        "Opinn íslenskur starfagagnagrunnur sem sameinar ÍSTARF21 (íslenska aðlögun ISCO-08) við ESCO. 578 starfaflokkar, 3.039 ESCO starfsheiti, 13.939 hæfnieiningar og 126.051 tenging. Aðgengilegt um opið REST API án auðkenningar.",
      url: "https://starfagrunnur.is",
      inLanguage: "is",
      license: "https://creativecommons.org/licenses/by/4.0/",
      isAccessibleForFree: true,
      keywords: [
        "ÍSTARF21",
        "ESCO",
        "ISCO-08",
        "starfaflokkar",
        "hæfni",
        "færni",
        "Ísland",
        "starfagrunnur",
        "opin gögn",
        "occupational classification",
      ],
      creator: {
        "@type": "Organization",
        "@id": "https://starfagrunnur.is/#org",
        name: "Peritus",
        url: "https://peritus.is",
      },
      publisher: { "@id": "https://starfagrunnur.is/#org" },
      dateModified: new Date().toISOString().slice(0, 10),
      isBasedOn: [
        {
          "@type": "CreativeWork",
          name: "ÍSTARF21",
          description: "Íslenskt starfaflokkunarkerfi, aðlögun ISCO-08",
          publisher: {
            "@type": "Organization",
            name: "Hagstofa Íslands",
            url: "https://hagstofa.is",
          },
        },
        {
          "@type": "CreativeWork",
          name: "ESCO — European Skills, Competences, Qualifications and Occupations",
          url: "https://esco.ec.europa.eu",
          license: "https://creativecommons.org/licenses/by/4.0/",
          publisher: {
            "@type": "Organization",
            name: "European Commission",
          },
        },
      ],
      distribution: [
        {
          "@type": "DataDownload",
          encodingFormat: "application/json",
          contentUrl: "https://starfagrunnur.is/api/v1/occupations",
          name: "REST API — occupations endpoint",
        },
        {
          "@type": "DataDownload",
          encodingFormat: "application/yaml",
          contentUrl: "https://starfagrunnur.is/openapi.yaml",
          name: "OpenAPI 3.1 specification",
        },
      ],
      variableMeasured: [
        "ÍSTARF21 occupation groups",
        "ESCO occupations",
        "ESCO skills",
        "essential and optional skill requirements",
      ],
    },
    {
      "@type": "WebSite",
      "@id": "https://starfagrunnur.is/#website",
      url: "https://starfagrunnur.is",
      name: "Starfagrunnur",
      inLanguage: "is",
      description:
        "Opinn gagnagrunnur og API um íslenskt starfakerfi, byggður á ÍSTARF21 og ESCO.",
      publisher: { "@id": "https://starfagrunnur.is/#org" },
      about: { "@id": "https://starfagrunnur.is/#dataset" },
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: "https://starfagrunnur.is/?q={search_term_string}#search",
        },
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "FAQPage",
      "@id": "https://starfagrunnur.is/#faq",
      mainEntity: [
        {
          "@type": "Question",
          name: "Hvað er ÍSTARF21?",
          acceptedAnswer: {
            "@type": "Answer",
            text:
              "ÍSTARF21 er íslenska starfaflokkunarkerfið, gefið út af Hagstofu Íslands árið 2021. Það er aðlögun á alþjóðlega ISCO-08 staðlinum og flokkar störf í fjögur stig: bálkur, deild, klasi og starfaflokkur.",
          },
        },
        {
          "@type": "Question",
          name: "Hvað er ESCO?",
          acceptedAnswer: {
            "@type": "Answer",
            text:
              "ESCO (European Skills, Competences, Qualifications and Occupations) er fjöltyngt flokkunarkerfi Evrópusambandsins yfir störf og hæfni. Það veitir einkvæm conceptUri auðkenni fyrir hvert starf og hverja hæfni, gefið út undir CC BY 4.0 leyfi.",
          },
        },
        {
          "@type": "Question",
          name: "Hvernig tengjast ÍSTARF21 og ESCO í Starfagrunni?",
          acceptedAnswer: {
            "@type": "Answer",
            text:
              "ESCO starfsheiti eru tengd ÍSTARF21 flokkum í gegnum sameiginlega ISCO-08 kóða. Hvert ESCO starf hefur iscoGroup eiginleika sem samsvarar 4. stigs ÍSTARF21 kóða, sem gefur 2.983 tengd starfsheiti af 3.039 í heildina.",
          },
        },
        {
          "@type": "Question",
          name: "Hvað er munurinn á dæmigerðri og viðbótar hæfni?",
          acceptedAnswer: {
            "@type": "Answer",
            text:
              "ESCO merkir hverja hæfni annaðhvort sem dæmigerða (essential — hluti af kjarnastarfslýsingu á evrópska vinnumarkaðinum) eða viðbótar (optional — getur skipt máli eftir sérhæfingu og samhengi). Hvorugt þýðir að einstakur starfsmaður þurfi alla hæfnina; listinn lýsir starfsprófílnum.",
          },
        },
        {
          "@type": "Question",
          name: "Þarf API-lykil til að nota þjónustuna?",
          acceptedAnswer: {
            "@type": "Answer",
            text:
              "Nei. API-ið er opið, aðeins lestur, og krefst engrar auðkenningar. Öll svör eru á JSON-sniði og kóðuð í UTF-8.",
          },
        },
        {
          "@type": "Question",
          name: "Hversu stór er gagnagrunnurinn?",
          acceptedAnswer: {
            "@type": "Answer",
            text:
              "578 ÍSTARF21 starfaflokkar í fjórum stigum (9 bálkar, 39 deildir, 121 klasar, 409 starfaflokkar). 3.039 ESCO starfsheiti á íslensku. 13.939 hæfnieiningar (10.715 færni, 3.219 þekking). 126.051 tenging milli starfsheita og hæfni.",
          },
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="is"
      className={`${playfair.variable} ${sourceSerif.variable} ${dmMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem("starfagrunnur-theme");if(t)document.documentElement.setAttribute("data-theme",t)}catch(e){}})()`,
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
